---
---
- hosts: all
  vars_prompt:
    - name: USERNAME
      prompt: enter user id that you want to unlock/password reset
      private: no

    - name: PASSWORD
      prompt: enter in a new password for your user account
      private: yes
      confirm: yes

  tasks:
  - name: Ensure user bob is present
    ansible.windows.win_user:
      name: "{{ USERNAME | trim }}"
      password: "{{ PASSWORD }}"
      update_password: always
      state: present
      groups:
        - Users

  - name: confirm user account is unlocked and can log in
    debug:
      msg:
        - "user account's password has been reset"