---
---
- hosts: all
  vars:
    USERNAME: "dick"
    PASSWORD: "happynewyear"

  tasks:
  - name: Ensure user {{ USERNAME }} is present and update password
    ansible.windows.win_user:
      name: "{{ USERNAME }}"
      password: "{{ PASSWORD }}"
      update_password: always
      state: present
      groups:
        - Users

  - name: confirm user account {{ USERNAME }} has been reset password
    debug:
      msg:
        - "user account's password has been reset"